config/routes.rb
WsReturn::Application.routes.draw do

  match '/ressources/delete/:id' => "ressources#pdestroy", :via => :post
  resources :ressources

  resources :events

  get "home/index"

  devise_for :users

  resources :promos

  resources :schools

  resources :votes

  match '/score/voteArticle' => "scores#voteArticle", :via => :post
  match '/score/unvoteArticle' => "scores#unvoteArticle", :via => :post

  match '/score/voteAcomment' => "scores#voteAcomment", :via => :post
  match '/score/unvoteAcomment' => "scores#unvoteAcomment", :via => :post

  match '/score/voteGossip' => "scores#voteGossip", :via => :post
  match '/score/voteAgainstGossip' => "scores#voteAgainstGossip", :via => :post
  match '/score/unvoteGossip' => "scores#unvoteGossip", :via => :post

  resources :scores

  
  resources :gossips do
    resources :gcomments
  end

  resources :authors

  resources :tags
  resources :articles do
    resources :acomments
  end

  match '/articles/delete/:id' => "articles#pdestroy", :via => :post
  match '/articles/filterbylogin/:login' => "articles#filterbylogin", :via => :post
  match '/articles/:id/acomments/delete/:id' => "acomments#pdestroy", :via => :post
  match '/events/:id/update' => "events#pupdate", :via => :post
  match '/users/:id/update' => "users#pupdate", :via => :post

  resources :jobs

  

  match '/groups/:id/savemember' => "groups#savemember", :via => :post
  
  resources :groups

  resources :users

  resources :api_session

  root :to => "home#index"

end

app/models/promo.rb
# == Schema Information
#
# Table name: promos
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  school_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Promo < ActiveRecord::Base
  attr_accessible :school_id, :title

  belongs_to :school
  has_many :users
end

app/controllers/promos_controller.rb
class PromosController < ApplicationController
  # GET /promos
  # GET /promos.json
  def index
    @promos = Promo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promos }
    end
  end

  # GET /promos/1
  # GET /promos/1.json
  def show
    @promo = Promo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/new
  # GET /promos/new.json
  def new
    @promo = Promo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promo }
    end
  end

  # GET /promos/1/edit
  def edit
    @promo = Promo.find(params[:id])
  end

  # POST /promos
  # POST /promos.json
  def create
    @promo = Promo.new(params[:promo])

    respond_to do |format|
      if @promo.save
        format.html { redirect_to @promo, notice: 'Promo was successfully created.' }
        format.json { render json: @promo, status: :created, location: @promo }
      else
        format.html { render action: "new" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promos/1
  # PUT /promos/1.json
  def update
    @promo = Promo.find(params[:id])

    respond_to do |format|
      if @promo.update_attributes(params[:promo])
        format.html { redirect_to @promo, notice: 'Promo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promos/1
  # DELETE /promos/1.json
  def destroy
    @promo = Promo.find(params[:id])
    @promo.destroy

    respond_to do |format|
      format.html { redirect_to promos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/promos_helper.rb
module PromosHelper
end

app/views/promos/_form.html.erb
<%= form_for(@promo) do |f| %>
  <% if @promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% @promo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :school_id %><br />
    <%= f.number_field :school_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promos/edit.html.erb
<h1>Editing promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<h1>Listing promos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>School</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promos.each do |promo| %>
  <tr>
    <td><%= promo.title %></td>
    <td><%= promo.school_id %></td>
    <td><%= link_to 'Show', promo %></td>
    <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
    <td><%= link_to 'Destroy', promo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<h1>New promo</h1>

<%= render 'form' %>

<%= link_to 'Back', promos_path %>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @promo.title %>
</p>

<p>
  <b>School:</b>
  <%= @promo.school_id %>
</p>


<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>